### ISSUE TITLE
ConnectionRefusedError when trying to connect to usbmuxd on Windows

### ISSUE THREAD

**Issue by issahamdan** [JJTech0130/TrollRestore#22]
An error occurred!
Traceback (most recent call last):
  File "pymobiledevice3\usbmux.py", line 167, in create_usbmux_socket
  File "pymobiledevice3\usbmux.py", line 111, in __init__
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trollstore.py", line 152, in main
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1077, in main
  File "click\core.py", line 943, in make_context
  File "click\core.py", line 1408, in parse_args
  File "click\core.py", line 2400, in handle_parse_result
  File "click\core.py", line 2362, in process_value
  File "pymobiledevice3\cli\cli_common.py", line 200, in udid
  File "pymobiledevice3\usbmux.py", line 448, in select_devices_by_connection_type
  File "pymobiledevice3\usbmux.py", line 410, in list_devices
  File "pymobiledevice3\usbmux.py", line 406, in create_mux
  File "pymobiledevice3\usbmux.py", line 174, in create
  File "pymobiledevice3\usbmux.py", line 169, in create_usbmux_socket
pymobiledevice3.exceptions.ConnectionFailedToUsbmuxdError

Press Enter to exit...

**Comment by JJTech0130** [comment]
Do you have iTunes for Windows installed?

**Comment by hmj1314** [comment]
I have the same issue

**Comment by hmj1314** [comment]
previously I succeeded, but now I have the same issue .
